services:
  api1: &api
    build: .
    hostname: api1
    depends_on:
      - db
    environment:
      PORT: 8080
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.4GB"

  api2:
    <<: *api
    hostname: api2
    environment:
      PORT: 8081

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.6GB"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "1.6GB"
